//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MarhabaDatabase
{
    using System;
    using System.Collections.Generic;
    
    public partial class bill
    {
        public long bill_id { get; set; }
        public string bill_code { get; set; }
        public System.DateTime bill_date { get; set; }
        public double total_bill { get; set; }
        public string user_name { get; set; }
        public string table_no { get; set; }
        public string type { get; set; }
        public Nullable<System.DateTime> timestamp { get; set; }
        public string customer_phone { get; set; }
        public Nullable<bool> payment_type { get; set; }
        public Nullable<bool> payed { get; set; }
        public Nullable<double> totalWithoutGST { get; set; }
        public string gst_percent { get; set; }
        public string FiscalInvoiceNumber { get; set; }
        public string QR_Code { get; set; }
    }
}
