//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MarhabaDatabase
{
    using System;
    using System.Collections.Generic;
    
    public partial class bill_item
    {
        public long id { get; set; }
        public string bill_id { get; set; }
        public string item_code { get; set; }
        public double item_qty { get; set; }
        public double total_bill { get; set; }
        public string type { get; set; }
    }
}
