//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MarhabaDatabase
{
    using System;
    using System.Collections.Generic;
    
    public partial class configuration
    {
        public int id { get; set; }
        public Nullable<double> gst { get; set; }
        public Nullable<int> last_id_synced { get; set; }
        public string ntn { get; set; }
        public string branchCode { get; set; }
    }
}
