//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MarhabaDatabase
{
    using System;
    using System.Collections.Generic;
    
    public partial class item
    {
        public int id { get; set; }
        public string item_id { get; set; }
        public string item_name { get; set; }
        public double item_price { get; set; }
        public string item_qty { get; set; }
        public string item_type { get; set; }
    }
}
