//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MarhabaDatabase
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class MarhabaEntities : DbContext
    {
        public MarhabaEntities()
            : base("name=MarhabaEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<reservation> reservations { get; set; }
        public virtual DbSet<table> tables { get; set; }
        public virtual DbSet<customer> customers { get; set; }
        public virtual DbSet<item> items { get; set; }
        public virtual DbSet<user_info> user_info { get; set; }
        public virtual DbSet<pending_order> pending_order { get; set; }
        public virtual DbSet<pending_deliveries> pending_deliveries { get; set; }
        public virtual DbSet<bill_item> bill_item { get; set; }
        public virtual DbSet<closing> closings { get; set; }
        public virtual DbSet<closing_view> closing_view { get; set; }
        public virtual DbSet<pending_payment> pending_payment { get; set; }
        public virtual DbSet<configuration> configurations { get; set; }
        public virtual DbSet<bill> bills { get; set; }
        public virtual DbSet<tcp_settings> tcp_settings { get; set; }
    }
}
