//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MarhabaDatabase
{
    using System;
    using System.Collections.Generic;
    
    public partial class reservation
    {
        public int table_no { get; set; }
        public string status { get; set; }
        public int persons { get; set; }
        public System.DateTime incoming_time { get; set; }
        public System.DateTime outgoing_time { get; set; }
    }
}
