//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MarhabaDatabase
{
    using System;
    using System.Collections.Generic;
    
    public partial class table
    {
        public int id { get; set; }
        public string table_name { get; set; }
        public Nullable<int> table_seats { get; set; }
    }
}
